import re

with open('/Users/rubenreneorozco/.gemini/antigravity/scratch/bar-exam-review/prototype.html', 'r', encoding='utf-8') as f:
    content = f.read()

new_topics = [
    "{id:94,subject:'Civil Procedure',rule:'Personal Jurisdiction – Forum State Statutes',trigger:'Analyzing personal jurisdiction in a federal diversity case.',notes:'*The Correct Rule:* A federal court sitting in diversity must apply the personal jurisdiction statutes of the forum state (the state in which the federal court is located).\\n\\n*The Misconception:* Thinking that the personal jurisdiction analysis in a federal diversity case depends on where the plaintiff is a citizen or where the cause of action arose.\\n\\n*Why You Got It Wrong:* You chose State A (plaintiff\\'s citizenship). Because the court was located in State B, it had to apply State B\\'s personal jurisdiction statutes.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:95,subject:'Civil Procedure',rule:'Personal Jurisdiction – Specific Jurisdiction & Minimum Contacts',trigger:'A defendant is served within 100 miles of the courthouse (bulge rule) for a standard state-law claim, but lacks minimum contacts with the forum state.',notes:'*The Correct Rule:* For specific jurisdiction to exist, the plaintiff\\'s claim must arise out of or closely relate to the defendant\\'s minimum contacts with the forum state. Vacationing once a year does not suffice for a claim arising from an out-of-state accident.\\n\\n*The Misconception:* Believing that a defendant can be subject to personal jurisdiction based on service within 100 miles of the courthouse (the \"bulge rule\") even if they lack minimum contacts.\\n\\n*Why You Got It Wrong:* You selected the 100-mile service rule. The court lacked specific jurisdiction because the accident happened in State C, and the defendant lacked purposeful availment in State A.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:96,subject:'Civil Procedure',rule:'Choice of Law – Erie Doctrine & Federal Common Law',trigger:'A federal court sitting in diversity must decide whether to apply a state substantive defense or federal common law.',notes:'*The Correct Rule:* Under the Erie doctrine, federal courts sitting in diversity must apply state substantive law and federal procedural law. If a state statute provides a substantive defense (like assumption of risk) and it is outcome-determinative, the federal court cannot replace it with federal common law.\\n\\n*The Misconception:* Assuming that if no valid federal statute or rule explicitly governs an area, a federal court is automatically free to apply federal common law.\\n\\n*Why You Got It Wrong:* You selected that the application of federal common law was proper because no federal rule governed. It was improper because it ignored a substantive, outcome-determinative state law.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:97,subject:'Constitutional Law – Justiciability',rule:'Ripeness vs. Mootness',trigger:'A plaintiff files a pre-enforcement challenge to a criminal ordinance that has not been enforced in 20 years.',notes:'*The Correct Rule:* Ripeness blocks a case where the plaintiff has not yet suffered actual harm or an imminent threat of harm. If a criminal ordinance has not been enforced for 20 years, a pre-enforcement challenge is unripe because prosecution is not imminent.\\n\\n*The Misconception:* Conflating a law that has not been enforced in a long time (Ripeness) with a dispute that has already been resolved or faded away (Mootness).\\n\\n*Why You Got It Wrong:* You selected Mootness. A case is moot if a live controversy used to exist but was resolved; here, a live controversy never blossomed in the first place because the client faced no imminent threat of prosecution.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:98,subject:'Constitutional Law – Commerce & Federal Power',rule:'Dormant Commerce Clause – Market Participant Exception',trigger:'A state owns a natural gas field and takes commercial bids, favoring local companies over out-of-state interests.',notes:'*The Correct Rule:* Under the Market Participant Exception, if a state is acting as a buyer or seller in the market (rather than a regulator), it is completely exempt from Dormant Commerce Clause restrictions and may favor its own citizens.\\n\\n*The Misconception:* Believing that a state law or action is unconstitutional under the Dormant Commerce Clause simply because it discriminates against out-of-state economic interests.\\n\\n*Why You Got It Wrong:* You selected that the state discriminated against interstate commerce. Because the state owned the natural gas field and was taking commercial bids, it was acting as a market participant and was free to choose the local company.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:99,subject:'Contracts',rule:'Statute of Frauds – Merchant Confirmation Exception (Quantity Term)',trigger:'A merchant sends a confirmation memo that satisfies the signature requirement, but completely omits the quantity of goods.',notes:'*The Correct Rule:* Under the UCC (≥ $500), a contract is only enforceable up to the quantity term stated in writing. While a merchant confirmation memo can satisfy the signature requirement against a non-signing recipient who fails to object, the writing must still contain a quantity term to be valid.\\n\\n*The Misconception:* Thinking that the failure to object to a written merchant confirmation cures all deficiencies under the UCC Statute of Frauds, or that a letterhead cannot satisfy a signature.\\n\\n*Why You Got It Wrong:* You noted that the supplier failed to object. However, because the manufacturer\\'s confirmation note completely omitted the quantity of motors, the contract was completely unenforceable under the Statute of Frauds.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:100,subject:'Criminal Law',rule:'Accomplice Liability – Exempted Necessary Parties',trigger:'A person gives aid or encouragement to a transaction, but the crime by definition requires multiple participants and the statute only imposes liability on one party.',notes:'*The Correct Rule:* When a crime by definition requires multiple participants (e.g., a sale or a bribe) but the criminal statute only imposes liability on one of those parties (e.g., the seller), the other necessary party (the buyer) is legally exempt from accomplice liability.\\n\\n*The Misconception:* Finding a party guilty of accomplice liability purely because they gave aid/encouragement to a transaction, without looking at the structure of the underlying crime.\\n\\n*Why You Got It Wrong:* You voted to convict based on a hardware store analogy. The student was the buyer in a narcotics sale; because the statute only criminalized the sale, the buyer is an exempted necessary party and must be acquitted.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:101,subject:'Criminal Law',rule:'Inchoate Crimes – Attempt & Mere Preparation',trigger:'A defendant unequivocally expresses intent to commit a crime and agrees to meet in 10 days to perform a transaction.',notes:'*The Correct Rule:* At common law, criminal attempt requires both specific intent and an overt act that goes beyond mere preparation, coming within dangerous proximity of completing the target offense.\\n\\n*The Misconception:* Believing that an unequivocal expression of intent to commit a crime satisfies the actus reus of criminal attempt.\\n\\n*Why You Got It Wrong:* You chose that the defendant was guilty because he unequivocally expressed his intent. Agreeing to meet in 10 days to perform a transaction is mere preparation, not an act dangerously close to possession.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:102,subject:'Evidence',rule:'Hearsay Exceptions – Recorded Recollection vs. Refreshing Recollection',trigger:'A witness\\'s memory cannot be refreshed, but they made an accurate record when the event was fresh (FRE 803(5)).',notes:'*The Correct Rule:* Under FRE 803(5), if a witness\\'s memory cannot be refreshed but they made an accurate record when the event was fresh, the record may be read into evidence by the proponent, but it may only be received as an exhibit if offered by an adverse party.\\n\\n*The Misconception:* Believing that if a document qualifies under the Hearsay exception for Recorded Recollection, the proponent can introduce the document itself as an exhibit.\\n\\n*Why You Got It Wrong:* You chose to overrule both objections. The court should have let the prosecutor have the witness read it, but sustained the objection to entering the diary itself into evidence.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:103,subject:'Evidence',rule:'Character Evidence – Homicide / First Aggressor Rebuttal',trigger:'In a homicide case, the defendant claims the victim lunged with a knife (self-defense) but does not offer explicit character evidence attacking the victim.',notes:'*The Correct Rule:* In a homicide case, if the defendant introduces any evidence (including their own testimony) that the victim was the first aggressor, the prosecution may respond on rebuttal with reputation or opinion evidence of the victim\\'s peaceful character (FRE 404(a)(2)(C)).\\n\\n*The Misconception:* Believing that the prosecution can only introduce evidence of a victim\\'s good character if the defendant has first introduced explicit character evidence attacking the victim.\\n\\n*Why You Got It Wrong:* You selected that the evidence was inadmissible because the defendant hadn\\'t offered a character trait. The defendant\\'s self-defense testimony claiming the victim lunged with a knife triggered the \"first aggressor\" exception, opening the door for the prosecution.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:104,subject:'Real Property',rule:'Recording Acts – Notice Jurisdictions & Inquiry Notice',trigger:'A subsequent purchaser buys land and records a warranty deed, but someone else is physically possessing/living on the property under an unrecorded deed.',notes:'*The Correct Rule:* In a notice jurisdiction, a subsequent bona fide purchaser (BFP) takes priority over a prior unrecorded interest only if they purchase without notice. Notice includes inquiry notice: a buyer is charged with knowledge of what a physical inspection of the land would reveal.\\n\\n*The Misconception:* Focusing on whether a deed is a quitclaim or a warranty deed to determine priority, or overlooking physical possession as a source of notice.\\n\\n*Why You Got It Wrong:* You selected that a warranty deed for value beats a quitclaim deed without consideration. While true on paper, because the son was openly living on and working the farm, the friend was on inquiry notice of the son\\'s unrecorded deed, stripping the friend of BFP status.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:105,subject:'Torts',rule:'Vicarious Liability & Dram Shop Laws – Social Hosts',trigger:'A non-commercial social host over-serves alcohol to a guest who then causes an injury.',notes:'*The Correct Rule:* At common law, the consumption of alcohol—not the serving of it—is the proximate cause of a third party\\'s injuries. Unless a jurisdiction\\'s Dram Shop statute explicitly includes social hosts, commercial dram-shop acts apply only to commercial sellers of alcohol.\\n\\n*The Misconception:* Believing that statutory Dram Shop liability or general proximate cause principles extend common-law negligence liability to non-commercial social hosts who over-serve alcohol.\\n\\n*Why You Got It Wrong:* You selected that the subsequent bar\\'s actions were a superseding cause. The host was actually not liable from the jump because the jurisdiction followed the common law for non-commercial servers, meaning the host owed no legal duty for the injuries caused by the guest.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:106,subject:'Torts',rule:'Private Nuisance – Substantial Interference & Abnormal Sensitivity',trigger:'A business\\'s utility use disrupts a neighbor\\'s business, but the interference only causes harm because the neighbor is engaging in an abnormally sensitive use of their property.',notes:'*The Correct Rule:* Private nuisance requires a substantial and unreasonable interference with the use and enjoyment of land. If the interference only causes harm because the neighbor is engaging in an abnormally sensitive use of their property (like sensitive electronic equipment), there is no substantial interference under objective standards.\\n\\n*The Misconception:* Assuming that a business is automatically liable in nuisance or strict liability if its high-voltage utility use disrupts a neighbor\\'s business.\\n\\n*Why You Got It Wrong:* You initially looked at purely economic loss defenses. The correct barrier to recovery is that the plant\\'s operations would not affect a person of ordinary sensitivities, meaning no nuisance exists unless the interference is completely unreasonable regardless of the neighbor\\'s setup.',commonVsModern:'',date:new Date().toISOString()}"
]

new_topics_str = ",\n            ".join(new_topics)

# Pass a lambda to re.sub to avoid \g processing
content = re.sub(
    r'(\{id:93,.*?\}).*?\];',
    lambda m: m.group(1) + ',\n            ' + new_topics_str + '\n        ];',
    content,
    flags=re.DOTALL
)

# Update topics count
content = content.replace('93 Topics', '106 Topics')
content = content.replace('topic.id <= 93', 'topic.id <= 106')

# Update cleanup script
content = content.replace('allTopics = allTopics.filter(t => t.id <= 93);', 'allTopics = allTopics.filter(t => t.id <= 106);')

with open('/Users/rubenreneorozco/.gemini/antigravity/scratch/bar-exam-review/prototype.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Added 13 new topics successfully!")
