import re

with open('/Users/rubenreneorozco/.gemini/antigravity/scratch/bar-exam-review/prototype.html', 'r', encoding='utf-8') as f:
    content = f.read()

new_topics = [
    "{id:87,subject:'Civil Procedure',rule:'Jury Trial Demand upon Removal',trigger:'A case is removed from state court to federal district court, and a party wants a jury trial but didn\\'t demand it in state court.',notes:'Federal rules (FRCP 81(c)) govern the procedure for demanding a jury trial after removal. Even if state law deems the right waived because it wasn\\'t in the initial pleading, a party can preserve their 7th Amendment right by serving a written demand within the specific window provided under federal rules after removal.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:88,subject:'Civil Procedure',rule:'Choice of Law Rules Upon Venue Transfer',trigger:'A diversity case is transferred from one proper federal venue to another under 28 U.S.C. § 1404(a).',notes:'The receiving court must apply the substantive law—including the choice-of-law rules—that would have been applied by the original (transferor) court.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:89,subject:'Constitutional Law – Individual Rights',rule:'Exactions (Fifth Amendment Takings)',trigger:'A local government conditions the approval of a land-development or building permit on a landowner\\'s promise to dedicate property or resources to public use.',notes:'To avoid being classified as an unconstitutional Fifth Amendment taking, the government bears the burden of demonstrating: (1) An essential nexus between the imposed condition and a legitimate government interest, and (2) A rough proportionality (supported by individualized and quantifiable findings) between the impact of the condition on the landowner and the proposed development\\'s impact on the community.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:90,subject:'Constitutional Law – Individual Rights',rule:'Procedural Due Process & Standards of Proof',trigger:'An individual faces deprivation of life, liberty, or property by the government, such as a judge with a conflict of interest, or termination of parental rights.',notes:'Neutral Decision-Maker: Due process requires a neutral, unbiased decision-maker. A judge\\'s failure to recuse themselves when they have a direct personal stake violates this.\\nTermination of Parental Rights: Because the private interest in maintaining parental relationships is deeply fundamental, the Mathews v. Eldridge balancing test requires a higher standard of proof than a mere preponderance of the evidence. A state statute permitting permanent termination of parental rights based only on a preponderance of the evidence violates procedural due process; it typically requires clear and convincing evidence.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:91,subject:'Constitutional Law – Individual Rights',rule:'Equal Protection Against the Federal Government',trigger:'The federal government utilizes suspect classifications like race or national origin (e.g., in federal contract preferences).',notes:'While the Fourteenth Amendment\\'s Equal Protection Clause explicitly applies to states, the Due Process Clause of the Fifth Amendment contains an equal protection component that applies identical strict scrutiny standards to the federal government.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:92,subject:'Real Property',rule:'Inter Vivos Deeds vs. Wills (Delivery Presumptions)',trigger:'A grantor executes a deed but leaves it with an attorney, and later writes a conflicting will before passing away.',notes:'A valid inter vivos conveyance requires execution, delivery, and acceptance. Recording a deed raises a strong, rebuttable presumption of delivery, even if the physical deed remains with an attorney and is not handed to the grantee before the grantor\\'s death. Because a deed takes effect immediately upon delivery, a subsequent or conflicting testamentary gift in a will is invalid regarding that property.',commonVsModern:'',date:new Date().toISOString()}",
    "{id:93,subject:'Real Property',rule:'Easement Classifications',trigger:'A question tests the nature of an easement (e.g., who it benefits, what it allows, or how it was created).',notes:'In Gross: Benefits the holder personally rather than a parcel of land; burden transfers with servient estate, benefit does not automatically attach to land.\\nAffirmative vs. Negative: Affirmative allows active use of servient estate; negative restricts servient owner\\'s lawful use of their land.\\nCreation: Can be express (Statute of Frauds), irrevocable license (estoppel), or implied (necessity/prior use).',commonVsModern:'',date:new Date().toISOString()}"
]

new_topics_str = ",\n            ".join(new_topics)
content = re.sub(r'(\{id:86,.*?\}).*?\];', r'\1,\n            ' + new_topics_str + '\n        ];', content, flags=re.DOTALL)

content = content.replace('86 Topics', '93 Topics')
content = content.replace('topic.id <= 86', 'topic.id <= 93')

with open('/Users/rubenreneorozco/.gemini/antigravity/scratch/bar-exam-review/prototype.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Added 7 new topics!")
