import re

with open('/Users/rubenreneorozco/.gemini/antigravity/scratch/bar-exam-review/prototype.html', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update option
option_html = '<option value="Constitutional Amendments">Constitutional Amendments</option>'
content = content.replace('<option value="Other">Other</option>', option_html + '\n                <option value="Other">Other</option>')

# 2. Update SUBJECTS
content = content.replace("'Business Entities'", "'Business Entities', 'Constitutional Amendments'")

# 3. New Topics
new_topics = [
    "{id:94,subject:'Constitutional Amendments',rule:'4th Amendment - Threshold Issues',trigger:'Police search a location or item and defendant attempts to challenge it.',notes:'• Does the defendant have standing? (reasonable expectation of privacy — Katz test)\\n• Was there government action? (private searches don\\'t trigger 4th Amendment)',commonVsModern:'',date:new Date().toISOString()}",
    "{id:95,subject:'Constitutional Amendments',rule:'4th Amendment - Searches',trigger:'Police conduct a search with or without a warrant.',notes:'• Warrant requirement — probable cause + particularity\\n• Exceptions to warrant requirement:\\n  - Consent (voluntary, no coercion)\\n  - Search incident to lawful arrest (Chimel — person + grabbable area)\\n  - Plain view (lawful vantage point + immediately apparent)\\n  - Exigent circumstances (hot pursuit, emergency, evanescent evidence)\\n  - Automobile exception (probable cause to believe contraband)\\n  - Terry stop & frisk (reasonable suspicion + safety)\\n  - Inventory search\\n  - Protective sweep',commonVsModern:'',date:new Date().toISOString()}",
    "{id:96,subject:'Constitutional Amendments',rule:'4th Amendment - Special Contexts',trigger:'Police search a phone, tracking data, or special administrative area.',notes:'• Third-party doctrine (phone records, bank records — no REP)\\n• Digital/cell phones → Riley (warrant required for cell phone search incident to arrest)\\n• GPS tracking → Jones/Carpenter (prolonged surveillance = search)\\n• Curtilage vs. open fields\\n• Administrative/school searches (lower standard)',commonVsModern:'',date:new Date().toISOString()}",
    "{id:97,subject:'Constitutional Amendments',rule:'4th Amendment - Seizures',trigger:'Police stop or detain an individual.',notes:'• When does a seizure occur? (reasonable person feels free to leave)\\n• Terry stop vs. arrest — level of suspicion required\\n• Pretextual stops (Whren)',commonVsModern:'',date:new Date().toISOString()}",
    "{id:98,subject:'Constitutional Amendments',rule:'4th Amendment - Exclusionary Rule',trigger:'Evidence is obtained in violation of the 4th Amendment.',notes:'• Evidence obtained in violation → suppressed\\n• Exceptions: Good faith, inevitable discovery, independent source, attenuation (Wong Sun)\\n• Fruit of the poisonous tree',commonVsModern:'',date:new Date().toISOString()}",
    "{id:99,subject:'Constitutional Amendments',rule:'5th Amendment - Self-Incrimination',trigger:'Police question a suspect.',notes:'• Miranda warnings — trigger: custody + interrogation\\n• Custody = reasonable person would not feel free to leave\\n• Interrogation = express questioning or its functional equivalent\\n• Invocation — must be clear and unambiguous\\n• Waiver — knowing, voluntary, intelligent\\n• Public safety exception (Quarles)\\n• Miranda applies to testimonial evidence only (not blood, DNA, handwriting)',commonVsModern:'',date:new Date().toISOString()}",
    "{id:100,subject:'Constitutional Amendments',rule:'5th Amendment - Double Jeopardy',trigger:'Defendant is prosecuted multiple times for the same or similar offense.',notes:'• Attaches when jury is sworn in (or first witness sworn in a bench trial)\\n• Same offense test — Blockburger (two offenses = same if each doesn\\'t require proof of element the other doesn\\'t)\\n• Separate sovereigns exception (state + federal prosecution OK)\\n• Exceptions: mistrial for manifest necessity, hung jury, appeal by defendant',commonVsModern:'',date:new Date().toISOString()}",
    "{id:101,subject:'Constitutional Amendments',rule:'5th Amendment - Takings Clause',trigger:'Government seizes or heavily regulates private property.',notes:'• Private property taken for public use → just compensation required\\n• Physical taking vs. regulatory taking (Penn Central)\\n• Per se taking: permanent physical occupation; total economic wipeout\\n• Trigger: gov\\'t action that destroys all economic value',commonVsModern:'',date:new Date().toISOString()}",
    "{id:102,subject:'Constitutional Amendments',rule:'5th Amendment - Grand Jury / Due Process (5th)',trigger:'Defendant is indicted for a federal serious crime.',notes:'• Federal right to grand jury indictment for serious crimes\\n• Not incorporated to states',commonVsModern:'',date:new Date().toISOString()}",
    "{id:103,subject:'Constitutional Amendments',rule:'6th Amendment - Right to Counsel',trigger:'Defendant is formally charged and interacts with police or court.',notes:'• Attaches at all critical stages after formal charges\\n• Critical stages: arraignment, preliminary hearing, post-indictment interrogation, plea, sentencing\\n• Does NOT attach during pre-charge investigation (Rothgery line)\\n• Deliberate elicitation standard post-attachment (Massiah)\\n• Offense-specific — attaches only to the charged offense',commonVsModern:'',date:new Date().toISOString()}",
    "{id:104,subject:'Constitutional Amendments',rule:'6th Amendment - Effective Assistance of Counsel',trigger:'Defendant claims their lawyer made a mistake that affected the trial or plea.',notes:'• Strickland test: (1) deficient performance + (2) prejudice\\n• Prejudice = reasonable probability of different outcome\\n• Applies at trial AND plea bargaining (Lafler/Frye)',commonVsModern:'',date:new Date().toISOString()}",
    "{id:105,subject:'Constitutional Amendments',rule:'6th Amendment - Right to Jury Trial',trigger:'Defendant is charged with an offense and requests a jury.',notes:'• Serious offenses (> 6 months potential imprisonment)\\n• 6-person jury minimum; must be unanimous (federal + Ramos → state)\\n• Trigger: petty vs. serious offense distinction',commonVsModern:'',date:new Date().toISOString()}",
    "{id:106,subject:'Constitutional Amendments',rule:'6th Amendment - Speedy Trial',trigger:'A significant delay occurs before the defendant goes to trial.',notes:'• Barker v. Wingo balancing: length of delay, reason, assertion of right, prejudice',commonVsModern:'',date:new Date().toISOString()}",
    "{id:107,subject:'Constitutional Amendments',rule:'6th Amendment - Confrontation Clause',trigger:'Prosecution attempts to introduce an out-of-court statement without the declarant present.',notes:'• Right to cross-examine witnesses\\n• Crawford — testimonial hearsay requires opportunity to cross-examine\\n• Dying declarations exception',commonVsModern:'',date:new Date().toISOString()}",
    "{id:108,subject:'Constitutional Amendments',rule:'6th Amendment - Other 6th Rights',trigger:'Issues regarding trial transparency or witnesses.',notes:'• Public trial\\n• Notice of charges\\n• Compulsory process (subpoena witnesses)',commonVsModern:'',date:new Date().toISOString()}",
    "{id:109,subject:'Constitutional Amendments',rule:'14th Amendment - Due Process — Procedural',trigger:'Government deprives life, liberty, or property.',notes:'• Liberty interests: physical freedom, fundamental rights, protected state-created interests\\n• Property interests: legitimate claim of entitlement\\n• Process required: Mathews v. Eldridge balancing (private interest + risk of error + gov\\'t interest)',commonVsModern:'',date:new Date().toISOString()}",
    "{id:110,subject:'Constitutional Amendments',rule:'14th Amendment - Due Process — Substantive',trigger:'Government restricts a right for all people.',notes:'• Fundamental rights → strict scrutiny (necessary to compelling interest)\\n• Non-fundamental → rational basis (rationally related to legitimate interest)\\n• Fundamental rights: voting, travel, privacy, marriage, contraception, family relations\\n• Dobbs — abortion no longer fundamental right',commonVsModern:'',date:new Date().toISOString()}",
    "{id:111,subject:'Constitutional Amendments',rule:'14th Amendment - Equal Protection',trigger:'Government treats different classes of people differently.',notes:'• Strict scrutiny → race, national origin, alienage (most cases), fundamental rights\\n• Intermediate scrutiny → sex/gender, legitimacy\\n• Rational basis → everything else (age, disability, wealth, sexual orientation historically — post-Obergefell unclear)\\n• Trigger facts: facial classification vs. facially neutral law with discriminatory intent + impact (Washington v. Davis)',commonVsModern:'',date:new Date().toISOString()}",
    "{id:112,subject:'Constitutional Amendments',rule:'14th Amendment - Incorporation',trigger:'A state infringes on a right guaranteed by the Bill of Rights.',notes:'• Bill of Rights applied to states through 14th Amendment Due Process\\n• Selective incorporation — right must be fundamental to ordered liberty\\n• Nearly all rights now incorporated (grand jury indictment is a key exception)',commonVsModern:'',date:new Date().toISOString()}",
    "{id:113,subject:'Constitutional Amendments',rule:'14th Amendment - State Action Doctrine',trigger:'A private individual or corporation violates a constitutional right.',notes:'• 14th Amendment only applies to government actors\\n• Exceptions: public function doctrine, entanglement/nexus',commonVsModern:'',date:new Date().toISOString()}"
]

new_topics_str = ",\n            ".join(new_topics)
content = re.sub(r'(\{id:93,.*?\}).*?\];', r'\1,\n            ' + new_topics_str + '\n        ];', content, flags=re.DOTALL)

# Update topics count
content = content.replace('93 Topics', '113 Topics')
content = content.replace('topic.id <= 93', 'topic.id <= 113')

with open('/Users/rubenreneorozco/.gemini/antigravity/scratch/bar-exam-review/prototype.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Added 20 constitutional amendment topics")
