import json
import re

with open('/Users/rubenreneorozco/.gemini/antigravity/scratch/bar-exam-review/prototype.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Replace "76 Topics" with "86 Topics"
content = content.replace('76 Topics to Master', '86 Topics to Master')
content = content.replace('Bar Exam Review - 76 Topics', 'Bar Exam Review - 86 Topics')
content = content.replace('topic.id <= 76', 'topic.id <= 86')
content = content.replace('// Update original 76 topics', '// Update original 86 topics')

new_topics_js = """            {id:77,subject:'Contracts',rule:'Third-Party Beneficiaries vs. Substituted Contracts',trigger:'An agreement is made between two contracting parties where a third-party business or individual stands to profit (e.g., a distributor buying a prize car from a local dealership). Later, the original parties modify the deal or settle for cash, cutting the third party completely out of the transaction.',notes:'* Black-Letter Law: Only intended third-party beneficiaries have standing to enforce a contract; incidental beneficiaries do not. To be an intended beneficiary, the contracting parties must have had the explicit or implied intent to confer a direct benefit on the third party at the time of formation.\\n* Vesting Nuance: Even if a party is an intended beneficiary, their rights must vest before they can sue to prevent a modification or rescission. Rights vest when the beneficiary: (1) manifests assent to the promise in a manner invited or requested by the parties, (2) brings suit to enforce the promise, or (3) materially changes their position in justifiable reliance on the promise.\\n* Bar Exam Trap: If the contract was fundamentally designed to benefit someone else, a party who merely stands to profit is a mere incidental beneficiary. Consequently, they have no standing to challenge the substituted contract (the cash payout arrangement) made between the original parties.',date:new Date().toISOString()},
            {id:78,subject:'Business Entities',rule:'Agent’s Duty of Loyalty & Principal\\'s Consent',trigger:'An agent uses a principal’s property for personal enjoyment or outside the strict terms of the employment contract (e.g., a celebrity stylist wearing the client\\'s clothes in public). The principal observes this behavior over time and says nothing, but later sues for a breach of fiduciary duty.',notes:'* Black-Letter Law: An agent owes the principal a strict fiduciary duty of loyalty, which includes the duty not to use the principal’s property for the agent\\'s own purposes or personal gain without the principal’s consent.\\n* The Consent Exception: A principal can consent to conduct that would otherwise breach the duty of loyalty. This consent does not have to be an express, written waiver; it can be implied through the principal\\'s conduct. If a principal has actual knowledge that the agent is using their property and consistently fails to object, the principal\\'s silence constitutes ratification or implied consent.\\n* Bar Exam Trap: Do not confuse a lack of monetary damage with a lack of breach. An agent can breach their duty of loyalty even if the principal loses $0. However, the claim fails strictly if the principal\\'s repeated failure to object created implied consent, legalizing the actions.',date:new Date().toISOString()},
            {id:79,subject:'Contracts',rule:'UCC Firm Offers vs. Option Contracts',trigger:'A merchant sends a signed email or written communication promising to keep an offer to buy or sell goods open for a specified period (e.g., 60 days). Before that time expires, the merchant tries to raise the price or revoke, but the buyer has already placed an order through an online system.',notes:'* Black-Letter Law (UCC Firm Offer): Under UCC § 2-205, an offer to buy or sell goods is irrevocable if: (1) the offeror is a merchant, (2) the offer is in a signed writing, and (3) it gives explicit assurances that the offer will be held open.\\n* Critical Nuances:\\n  - Consideration: Unlike a common-law option contract, a UCC firm offer does not require consideration to be binding.\\n  - Duration: A firm offer is irrevocable for the time stated, but if no time is stated, for a reasonable time. Crucially, the period of irrevocability cannot exceed 3 months (90 days). If a merchant promises to keep an offer open for 5 months without consideration, it is only legally irrevocable for the first 3 months.\\n  - Electronic Signatures: A typed name, initials, or a digital signature block on an email satisfies the "signed writing" requirement under modern merchant standards.',date:new Date().toISOString()},
            {id:80,subject:'Real Property',rule:'Defeasible Fees & Drafting Conveyances',trigger:'A client wants to convey land to an entity (like a school district) but wants to ensure the land is only used for a specific purpose (e.g., a running track). If the land stops being used for that purpose, the client wants the option or guarantee that ownership will revert.',notes:'* Fee Simple Determinable (FSD):\\n  - Trigger Words: Durational language—"so long as," "while," "during," "until."\\n  - Future Interest: Automatically terminates upon the happening of the event and reverts to the grantor. The grantor holds a Possibility of Reverter.\\n* Fee Simple Subject to Condition Subsequent (FSSCS):\\n  - Trigger Words: Conditional language + right of entry—"but if," "provided that," "on the condition that," coupled with an explicit statement that the grantor may re-enter and retake.\\n  - Future Interest: Does not automatically terminate. The grantor holds a Right of Entry / Power of Termination and must take affirmative legal action to evict the possessor once the condition is broken.',date:new Date().toISOString()},
            {id:81,subject:'Contracts',rule:'Capacity to Contract & Intoxication',trigger:'A person gets heavily intoxicated, draft/sends an offer to sell an asset for cheap, and regrets it the next day after sobering up. However, the buyer has already responded and accepted the offer via email before any revocation was attempted.',notes:'* Black-Letter Law: Voluntary intoxication is a valid defense to contract formation only if: (1) the intoxication was so severe that it deprived the person of the ability to understand the nature and consequences of the transaction, AND (2) the other party had reason to know of the intoxication.\\n* The "Reason to Know" Trap: If a person is thoroughly intoxicated but sends a perfectly coherent, typed email offer from the privacy of their home, the recipient has no visual or contextual clues indicating the intoxication.\\n* Bar Exam Application: If the buyer had no reason to know the owner was drunk, the contract is completely valid. The owner cannot escape the contract based on a lack of capacity.',date:new Date().toISOString()},
            {id:82,subject:'Evidence',rule:'Attorney-Client Privilege & Joint Consultations',trigger:'Prior to filing a personal injury lawsuit, a plaintiff\\'s attorney has the plaintiff visit a doctor solely to evaluate damages for the litigation. During a joint discussion, the plaintiff makes a damaging admission. At trial, the defense tries to call the doctor to testify about that statement.',notes:'* Black-Letter Law: The attorney-client privilege protects confidential communications between a client and their attorney (or the attorney\\'s representatives) made for the purpose of facilitating legal services.\\n* The Representative Extension (Critical Nuance): When an attorney hires a medical expert or doctor strictly for the purpose of evaluating a case or preparing for litigation (and not for medical treatment), that doctor acts as an agent/representative of the attorney. Therefore, communications made in the presence of that doctor remain entirely confidential under the attorney-client privilege.\\n* Physician-Patient Privilege Distinction: The physician-patient privilege only applies when a patient consults a doctor for medical diagnosis or treatment. It does not apply to purely legal evaluations.',date:new Date().toISOString()},
            {id:83,subject:'Evidence',rule:'The Best Evidence Rule & Personal Knowledge',trigger:'A party attempts to introduce a scanned copy or duplicate of a receipt into evidence. Simultaneously, they call an employee to testify about the specific contents or data written on the original receipt, even though the employee was not present for the transaction and is simply reading or repeating what the document says.',notes:'* Best Evidence Rule: Requires the production of an original writing, recording, or photograph to prove its contents. However, under FRE 1003, a duplicate/scanned copy is perfectly admissible to the same extent as an original unless a genuine question is raised about the original\\'s authenticity or it would be unfair to admit it.\\n* Personal Knowledge Requirement: A witness may not testify to a matter unless evidence is introduced sufficient to support a finding that the witness has personal knowledge of the matter (FRE 602). A witness cannot simply look at a document they have no personal involvement with and testify to its underlying factual contents.',date:new Date().toISOString()},
            {id:84,subject:'Evidence',rule:'Impeachment by Evidence of a Criminal Conviction (FRE 609)',trigger:'A witness testifies at trial. After they leave the stand, the opposing party attempts to introduce extrinsic evidence proving the witness was convicted of a crime involving dishonesty 11 years ago, without ever asking the witness about it while they were on the stand.',notes:'* Crimes of Dishonesty (No Discretion): Under FRE 609(a)(2), any prior conviction for a crime of dishonesty or false statement (e.g., perjury, fraud, embezzlement) must be admitted for impeachment purposes, regardless of whether it was a felony or misdemeanor, and the judge cannot balance prejudice under Rule 403.\\n* The 10-Year Rule: If more than 10 years have passed since the witness\\'s conviction or release from confinement (whichever is later), the conviction is stale. It is only admissible if: (1) its probative value substantially outweighs its prejudicial effect, and (2) the proponent gives reasonable written notice.\\n* Extrinsic Evidence Nuance: Unlike prior bad acts under Rule 608(b), a criminal conviction used to impeach a witness\\'s character for truthfulness may be proved by extrinsic evidence (like a certified record), and there is no strict requirement that the witness be confronted first on the stand.',date:new Date().toISOString()},
            {id:85,subject:'Real Property',rule:'Cotenants\\' Rights to Possession, Repairs, and Taxes',trigger:'Two relatives own a home as tenants in common. One lives out of state, and they agree the local relative will occupy the house. The occupying relative pays the property taxes (which are less than the home\\'s fair rental value) and pays for an emergency plumbing repair. Later, the occupying relative demands 50% reimbursement from the out-of-state cotenant.',notes:'* Right to Possession: Each cotenant has an absolute right to possess and enjoy the entire property. An occupying cotenant does not owe rent to non-occupying cotenants unless there has been an "ouster".\\n* Property Taxes / Mortgages: A cotenant who pays more than their share can generally seek contribution. Exception: If the occupying cotenant is the only one enjoying the property, they cannot get a reimbursement for taxes if the financial value of their sole occupancy (rental value) exceeds the amount paid for taxes.\\n* Repairs & Improvements: A cotenant has no right to compel contribution from other cotenants for necessary repairs or improvements in the absence of an express agreement. Instead, the cotenant who paid for repairs receives a credit or adjustment during a later partition action.',date:new Date().toISOString()},
            {id:86,subject:'Real Property',rule:'Future-Advances Mortgages & Priority',trigger:'A bank records a construction loan mortgage that explicitly states the bank will disburse money in monthly installments as building progresses. A third-party creditor later records a judgment lien against the borrower. Afterward, the bank makes its scheduled monthly advances to the borrower.',notes:'* Black-Letter Law: A future-advances mortgage secures a loan where funds are paid out over time rather than all at once. The priority of these later payments against intervening liens depends entirely on whether the advances are obligatory or optional.\\n* Obligatory Advances: If the bank is legally contractually committed to making the line of credit advances, the future advances retain the original recording date of the mortgage. They have absolute priority over any junior lien recorded in the interim.\\n* Optional Advances: If the disbursements are completely at the bank\\'s discretion, an advance made after the bank receives notice of an intervening judgment lien loses priority to that junior lien.',date:new Date().toISOString()}"""

search_str = "date:new Date().toISOString()}\\n        ];"
replace_str = "date:new Date().toISOString()},\\n" + new_topics_js + "\\n        ];"

content = content.replace(search_str, replace_str)

with open('/Users/rubenreneorozco/.gemini/antigravity/scratch/bar-exam-review/prototype.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Updated prototype.html successfully")
